workspace:
  base: .
  path: /

pipeline:
  build:
    image: gentoo/stage3-amd64
    commands:
      - emerge-webrsync -q
      - emerge -q spdlog meson poco boost yaml-cpp
      - meson build . && cd build && ninja

